name: Prettier code formatter and Jekyll build

on:
  pull_request:
    branches:
      - master
      - main
  push:
    branches:
      - master
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v4

      - name: Setup Node.js âš™ï¸
        uses: actions/setup-node@v4

      - name: Install Prettier ğŸ’¾
        run: npm install --save-dev --save-exact prettier @shopify/prettier-plugin-liquid


      - name: Create diff ğŸ“
        if: ${{ failure() }}
        run: |
          npx prettier . --write
          git diff -- . ':(exclude)package-lock.json' ':(exclude)package.json' > diff.txt
          npm install -g diff2html-cli
          diff2html -i file -s side -F diff.html -- diff.txt

      - name: Prettier Check ğŸ”
        id: prettier-check
        run: npx prettier . --check


      - name: Upload html diff â¬†ï¸
        id: artifact-upload
        if: ${{ failure() && steps.prettier-check.conclusion == 'failure' }}
        uses: actions/upload-artifact@v4
        with:
          name: HTML Diff
          path: diff.html
          retention-days: 7

      - name: Dispatch information to repository ğŸ—£ï¸
        if: ${{ failure() && steps.prettier-check.conclusion == 'failure' && github.event_name == 'pull_request' }}
        uses: peter-evans/repository-dispatch@v2
        with:
          event-type: prettier-failed-on-pr
          client-payload: '{"pr_number": "${{ github.event.number }}", "artifact_url": "${{ steps.artifact-upload.outputs.artifact-url }}", "run_id": "${{ github.run_id }}"}'

      # Add Python setup and virtual environment creation
      - name: Set up Python environment ğŸ
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Create virtual environment
        run: python3 -m venv .venv

      - name: Activate virtual environment and install Jupyter
        run: |
          source .venv/bin/activate
          pip install --upgrade pip
          pip install jupyter

      # Install Ruby and Gems for Jekyll
      - name: Install Ruby and Gems ğŸ’
        run: |
          gem install bundler
          bundle install

      # Format files with Prettier before building with Jekyll
      - name: Format with Prettier âœ¨
        run: npx prettier . --write

      # Build Jekyll Site ğŸ—ï¸
      - name: Build with Jekyll ğŸ—ï¸
        run: |
          source .venv/bin/activate
          export JEKYLL_ENV=production
          bundle exec jekyll build
